version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: monthly
    day: sunday
    time: "19:00"
    timezone: Asia/Tokyo
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: monthly
    day: sunday
    time: "19:00"
    timezone: Asia/Tokyo
