name: CI
on:
  pull_request_target:
    branches: [main]
  workflow_dispatch:
  schedule:
  - cron: 10 0 1 * *

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: stable
        check-latest: true
    
    - name: Generate KML
      run: go run main.go
      env:
        GCLOUD_API_KEY: ${{ secrets.GCLOUD_API_KEY }}
        TZ: 'Asia/Tokyo'

    - name: Prepare envs
      if: github.event_name != 'pull_request_target'
      id: env
      run: |
        echo "release_new_name=$(date +%Y/%m/%d)" >> $GITHUB_OUTPUT
        echo "release_new_tag=$(date +%Y%m%d)" >> $GITHUB_OUTPUT
        echo "release_new_asset_file=result-$(date +%Y/%m/%d).kml" >> $GITHUB_OUTPUT
        echo "release_new_draft=draft-$(date +%Y%m%d).md" >> $GITHUB_OUTPUT
      env:
        TZ: 'Asia/Tokyo'

    - name: Fetch previous Release KML
      if: github.event_name != 'pull_request_target'
      id: prev
      run: |
        latest_asset_url=$(gh api "repos/${{ github.repository }}/releases/latest" \
          --jq '.assets[0].browser_download_url')
        curl -LO ${latest_asset_url}
        echo "latest_file=$(gh api "repos/${{ github.repository }}/releases/latest" \
          --jq '.assets[0].browser_download_url')" >> $GITHUB_OUTPUT

    - name: Make Release draft
      if: github.event_name != 'pull_request_target'
      run: |
        diff_file=$(diff ${{ steps.prev.outputs.latest_file }} ${{ steps.env.outputs.release_new_asset_file }} \
        --ignore-matching-lines=".*description.*" \
        --ignore-matching-lines=".*name=\"住所\".*" \
        --ignore-matching-lines=".*name=\"ランキング\"" \
        --ignore-matching-lines=".*name=\"ランキング結果(5〜1位)\"" \
        --ignore-matching-lines=".*name=\"ライブラリ設置\"" \
        --ignore-matching-lines=".*coordinates.*" \
        --ignore-matching-lines=".*styleUrl.*" \
        -U 0)

        cat << EOS > ${{ steps.env.outputs.release_new_draft }}
        # 新規出店・退店

        \`\`\`diff
        ${diff_file}
        \`\`\`
        EOS

    - name: Create GitHub Release(pre)
      if: github.event_name != 'pull_request_target'
      uses: softprops/action-gh-release@v2
      with:
        body_path: ${{ steps.env.outputs.release_new_draft }}
        files: ${{ steps.env.outputs.release_new_asset_file }}
        name: ${{ steps.env.outputs.release_new_name }}
        prerelease: true
        tag_name: ${{ steps.env.outputs.release_new_tag }}
