name: make-kml
on:
  workflow_dispatch:
  schedule:
  - cron: 10 0 1 * *

jobs:
  make_kml:
    name: make-kml
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ">1.0"
        check-latest: true
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: prepare envs
      run: |
        RELEASE_NEW_NAME=$(date +%Y/%m/%d)
        RELEASE_NEW_TAG=$(date +%Y%m%d)
        RELEASE_NEW_ASSET_FILE=result-${RELEASE_NEW_TAG}.kml
        RELEASE_NEW_DRAFT=draft-${RELEASE_NEW_TAG}.md
        echo "RELEASE_NEW_NAME=${RELEASE_NEW_NAME}" >> $GITHUB_ENV
        echo "RELEASE_NEW_TAG=${RELEASE_NEW_TAG}" >> $GITHUB_ENV
        echo "RELEASE_NEW_ASSET_FILE=${RELEASE_NEW_ASSET_FILE}" >> $GITHUB_ENV
        echo "RELEASE_NEW_DRAFT=${RELEASE_NEW_DRAFT}" >> $GITHUB_ENV

    - name: make-kml
      env:
        GO111MODULE: on
        GOPATH: /home/runner/work/
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GCLOUD_API_KEY: ${{ secrets.GCLOUD_API_KEY }}
        RELEASE_NEW_NAME: ${{ env.RELEASE_NEW_NAME }}
        RELEASE_NEW_TAG: ${{ env.RELEASE_NEW_TAG }}
        RELEASE_NEW_ASSET_FILE: ${{ env.RELEASE_NEW_ASSET_FILE }}
        RELEASE_NEW_DRAFT: ${{ env.RELEASE_NEW_DRAFT }}
        TZ: 'Asia/Tokyo'
      run: .github/workflows/make-kml.sh

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        body_path: ${{ env.RELEASE_NEW_DRAFT }}
        files: ${{ env.RELEASE_NEW_ASSET_FILE }}
        name: ${{ env.RELEASE_NEW_NAME }}
        prerelease: true
        tag_name: ${{ env.RELEASE_NEW_TAG }}
