name: Check make-kml is successful
on:
  pull_request:
    branches:
      - main

jobs:
  make_kml:
    name: make-kml
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ">1.0"
        check-latest: true
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@master

    - name: make-kml
      env:
        GO111MODULE: on
        GOPATH: /home/runner/work/
        TZ: 'Asia/Tokyo'
      run: go run main.go
